### ISSUE TITLE
As a Husarion ROSbot user, I want to use ROS2 on my ROSbot so I can communicate with ROS2 nodes.

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-roadmap#120]
## Description

Husarion's ROSbot firmware uses ROS1 under the hood. It is theoretically possible to use the `ros1_bridge` to work with the ROSbot, however a native ROS2 implementation is preferred.

A ROS2 port of the [`rosbot-firmware-new`](https://github.com/husarion/rosbot-firmware-new/) should be done. 
Most of the work is just changing the definitions of the publishers/subscribers in [`main.cpp`](https://github.com/husarion/rosbot-firmware-new/blob/master/src/main.cpp) using rclcpp.

## Test Plan

* Manual QA in a Quip doc highlighting how the firmware was built and installed as well as running example nodes.
* Run the already built in `test_main.cpp`.

## Documentation Plan

* Docstrings
* Internal Quip doc with the QA

## Release Plan

* Gitfarm

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed.
* [ ] Release plan has been completed.

Once all above items are checked, this story can be moved to done.

## Resources

* [ROS2 porting question for Husarion](https://github.com/husarion/rosbot-firmware-new/issues/2)

**Comment by zmichaels11** [comment]
I think this is actually a spike

**Comment by thomas-moulard** [comment]
Deprioritized.
