### ISSUE TITLE
As a rosbag2 user, I want to use compression so that I can compress my bags

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-roadmap#124]
## Description

The de/compression features need to be exposed to a rosbag2 user through the CLI. 
The compression flag will be `-c`.

The compression keys of `compression_type` and `compression_format` also need to be add to `rosbag2_storage::bag_metadata`. 

Tasks:

* [x] Enable compression in the reader
* [x] Enable compression in the writer
* [x] Add compression options that can be used in rosbag2_cpp and rosbag2_storage
* [x] Add a compression flag to the `rosbag2_transport` package
* [x] Add a compression flag to the `ros2bag` CLI 

## Test Plan

* [x] Update `rosbag2_storage` unit tests for metadata.
* [x] Unit test with a mock compressor to check that the compression has been called in the reader.
* [x] Unit test with a mock decompressor to check that decompression has been called in the writer.
* [x] Argparse unit test that checks the proper flags are propagated to the `rosbag2_transport` layer.

An E2E test is in #163

## Documentation Plan

Update the `ros2bag` argparse epilog and help docstrings.

## Release Plan

* Merge into master branch of `rosbag2`

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by zmichaels11** [comment]
- [ ] Add `SequentialCompressionWriter` PR: https://github.com/ros2/rosbag2/pull/260

**Comment by zmichaels11** [comment]
- [ ] PR: https://github.com/ros2/rosbag2/pull/263

**Comment by thomas-moulard** [comment]
Punted from sprint #11 to sprint #12 on 2020-02-03
