### ISSUE TITLE
Engage OSRF to discuss release procedures for Python packages to not skip testing repos

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-roadmap#129]
## Description

* [ ] Setup a meeting with Open Robotics, to talk about how the impact of `colcon` and `rosdep` changes can be better evaluated
* [ ] Write down a proposal, e.g. should we contribute e2e tests? Help with CI automation?

Verify if these are the only tools we need to monitor.

## Documentation Plan

* Proposal for better e2e testing of the developer architecture

## Acceptance Criteria

* [ ] Plan has been reviewed, and agreed upon. No need to commit to timelines at this point.
* [ ] User stories and epics have been added to `aws-roadmap`

Once all above items are checked, this story can be moved to done.

**Comment by zmichaels11** [comment]
TODO: Refile as a Spike

**Comment by emersonknapp** [comment]
Not a priority right now
