### ISSUE TITLE
Reach feature parity between GH Actions and ci.ros2.org

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-roadmap#133]
## Description

Make GH actions a reasonable replacement for `ci.ros2.org`.
All our CI needs should be covered by GH actions, and `*.ros2.org` should just handle the Debian/Bloom CD part.

## Completion Criteria

All our CI needs are covered by the GH actions.

**Comment by emersonknapp** [comment]
This is no longer an explicit goal of this project. We match, incrementally, features that users want, but don't need to track parity.
