### ISSUE TITLE
ROSBag2 Writer FSM Tests

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#134]
## Description

The rosbag2_cpp Writer utilizes a FSM transitioning between:

`ctor` -> `open `-> [`create_topic` | `remove_topic` | `write`] -> `close` -> `dtor`

There should be an automated test validating the transitions between these states.

## Test Plan

* Unit test for Writer state changes

## Release Plan

* Merge into master branch of `rosbag2`

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by emersonknapp** [comment]
Closing in favor of https://github.com/ros2/rosbag2/issues/195
