### ISSUE TITLE
[1d] Write user story explaining how to remove get_metadata as a required function for rosbag2 plugins

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-roadmap#135]
## Description
ROSBag2 requires implementation of the function `get_metadata` for all plugins. As a side-effect of the rosbag splitting changes, the `Writer` and `Reader` are now responsible for handling of metadata instead of the plugin, so `get_metadata` should be removed. However `rosbag2_bag_v2` requires this function to generate a compatible metadata file to read ROS1 bagv2 files for read and play back.

## Spike Timeboxing
1 Days

## Spike Outcome
* User story
* Update https://github.com/ros2/rosbag2/issues/213 with resolution plan

## Goals
* [ ] Determine how to resolve `get_metadata` function

**Comment by emersonknapp** [comment]
The architecture here has changed, removing this spike
