### ISSUE TITLE
[2d] ARM64 Kinesis Video Stream Demo

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#137]
## Description

Demonstrate Kinesis Video Streams via a ros2 node on an ARM64 system.

This requires cross-compiling with a custom toolchain.

## Test Plan

Manual reproduction of the prodived demo

## Documentation Plan

* README with complete instructions that a second person can repro

## Release Plan

* Check in code and hand off

## Acceptance Criteria

* [x] Cross-compile and run the ROS2 minimal core up to rclcpp
* [x] Show the demo_nodes_cpp running on the target board
* [x] Cross-compile and deploy the AWS C++ SDK dependencies (zlib, openssl, curl)
* [x] Cross-compile aws_common ros2 package
* [x] Show a basic kinesis text data stream working from the target board
* [x] Cross compile kinesis video producer dependencies (tinyxml, log4cplus)
* [x] Cross-compile kinesis video producer
* [x] cross-compile aws-robotics kinesis manager and kinesis node
* [ ] create a ROS2 camera publisher node to feed the kinesis streamer
* [ ] Watch a kinesis video stream from the target board on the AWS interface
* [ ] All above builds are perfectly repeatable with a minimal number of steps

Once all above items are checked, this story can be moved to done.

## Resources

* New tool https://github.com/emersonknapp/ros2-toolchain-crosscompile
* Discourse discussion https://discourse.ros.org/t/c-c-minimal-source-tree-only-ros2-variant/11760/2

**Comment by thomas-moulard** [comment]
Punted from sprint #11 to sprint #12 on 2020-02-03

**Comment by emersonknapp** [comment]
This was demonstrated
