### ISSUE TITLE
[0.5d] Update System Metrics Design Doc

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#145]
## Description

There are a few minor changes that need to be reflected in the system metrics design doc, since implementation. 

## Spike Timeboxing

0.5 days

## Spike Outcome

 * Updated design doc (shareable)
 * Updated, shareable, plantuml diagrams

## Goals

* update documentation before creating the ROS2 Tooling WG presentation

**Comment by emersonknapp** [comment]
No longer relevant
