### ISSUE TITLE
Rosbag2 Compression Streaming

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-roadmap#146]
## Description
As a Rosbag2 User, I want Rosbag2 to stream-compress my rosbags so I can minimize the amount of RAM consumed by the compression.

Rosbag2_compression needs to use a buffer streaming pattern to compress bagfiles so only `buffer_size` memory is required.

## Test Plan
* Unit test counting buffers used in compression
* Update unit tests to compress a file large enough to fill more than 1 buffer
* Add unit test to compress a file that fits in a single buffer.

## Documentation Plan
* N/A at the moment

## Release Plan
* check in PR

## Acceptance Criteria

PROMPT (REMOVE-ME): Clearly defined checklist of things that need to be done to call this task complete. Can include items from all above sections.

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources
* [Streaming compression - HowTo](https://facebook.github.io/zstd/zstd_manual.html#Chapter8)

**Comment by emersonknapp** [comment]
Closing in favor of https://github.com/ros2/rosbag2/issues/295
