### ISSUE TITLE
[2d] ROS2 Topic Statistics Design Doc

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#148]
## Description

Define the design doc for the ROS2 Message Metrics project. This should be similar to the ROS2 Runtime Metrics design doc and pull heavily from the existing 1-pager (see internal project folder).

## Spike Timeboxing

2 Days

Deliverables

 * Design doc
 * Scheduled meeting to review doc

**Comment by emersonknapp** [comment]
This requires action -

Talk to OSRF - find out if they think we should write a design document after the fact for the feature that we have built.

**Comment by emersonknapp** [comment]
Not seeing value in post-hoc design doc considering we already have concept and tutorial wiki pages
