### ISSUE TITLE
As a rosbag2 user, I want to know how much system resources rosbag2 is using so I can generate performance benchmarks

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-roadmap#150]
## Description

Provide benchmarking data for rosbag2 performance and compare against ROS1. The following performance data should be reported:

* system CPU usage
* system Memory usage
* rosbag CPU usage
* rosbag Memory usage
* Compression Ratio (where experiment applicable)
* Dropped messages (unrelated to potential DDS issues)
* Realtime playback (specifically if there are any significant delays playing back compressed data)

**Experiments**

|Mode        |  ROS1                 |  ROS2 |
|--------------|------------------------|-----------------------|
| Record     |  Uncompressed  |  Uncompressed |
|  Record    |  File Compression      | File Compression      |
|  Playback |  Uncompressed  | Uncompressed  |
|  Playback    |  File Compression      | File Compression      |

Using the [RoboMaker Navigation and Person Detection Sample App](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection) package, we can baseline ROS1 rosbag performance, generate a bag file to use for replay, and reuse this file in order to baseline rosbag2 performance.

The goal is to provide a baseline for rosbag performance and comparison with rosbag2 given the experiment matrix above. 

## Test Plan

* Manual documentation in a Quip Doc demonstrating setup and usage as well as results for each experiment.

## Documentation Plan

Quip doc explaining how to generate the reports

## Release Plan

This does not have a release candidate.

## Acceptance Criteria

* [ ] Developed means to generate reports, e.g., scripts / logging tools, etc
* [ ] Documented workflow in quip doc

Once all above items are checked, this story can be moved to done.

## Resources

* [Initial PR for performance testing](https://github.com/ros2/rosbag2/pull/244)
* [ROS2_Performance_Testing_Tools](https://code.amazon.com/packages/ROS2_Performance_Testing_Tools/trees/mainline/--/) using `plot_system_stats.py` and `log_system_stats.py`

**Comment by zmichaels11** [comment]
I think this is actually a spike

**Comment by piraka9011** [comment]
Consider using System Metrics Collector instead.
Use the sample apps to test.

**Comment by piraka9011** [comment]
A PR in rosbag2 with a performance test proposal was opened [here](https://github.com/ros2/rosbag2/pull/244).

**Comment by dabonnie** [comment]
@zmichaels11 @piraka9011 

>Dropped messages (in rosbag2 and not in DDS layer)

Is this currently possible in rosbag2?

**Comment by dabonnie** [comment]
Note: ros2 message compression was removed from the test matrix because it is not yet implemented
