### ISSUE TITLE
ROS2 Performance Testing Improvements

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#153]
## Description

Contribute the tools created, to benchmark ROS2 Crystal, back to the ApexAI performance testing repo. The tools consist of three parts:

1). Python scripts to run the ApexAi performance testing with specific arguments and saving the output data into a specific file format (directory structure and file name). 

2). Python scripts to plot aggregated results of the performance testing output from #113 

3). Python scripts to collect, aggregate, and plot system cpu + memory and test process cpu + memory.

Items #1 and #2 should be easy to contribute back to the ApexAI repo. Note: these scripts require the [following changes](https://github.com/dabonnie/performance_test/commit/18952e71e3ee1d0969b52a647993d317d62f284d) in order to properly name the experiment files.

Item #3 is tricky: we use these scripts internally (for ROS projects, etc) as a simple means to benchmark an application. We currently have approval to open source the scripts, but 
it's unclear if we should require the ApexAI test to pull in our scripts as a dependency or just copy them to the project. Conversely, to use the scripts standalone (common use case) the ApexAi test package is a large dependency. 

## Documents

* [Internal doc link](https://quip-amazon.com/AZOPAHJOU2FV)
* [File name changes](https://github.com/dabonnie/performance_test/commit/18952e71e3ee1d0969b52a647993d317d62f284d)

## Completion Criteria

 - [ ] Contribute scripts to ApexAi project
 - [ ] Sync with OSRF build team to use aggregated metrics and plots

**Comment by emersonknapp** [comment]
Closing in favor of internal tracking
