### ISSUE TITLE
Tooling Operational Excellence

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-roadmap#155]
## Description

Track improvements around better monitoring of builds and release management.

## Documents

REMOVE ME: Link or include any designs that inform this Epic's completion criteria.

## Completion Criteria

REMOVE ME: Instead of creating a list here, start creating issues under this epic, this will be the TO-DO list for this Epic. When all children are done, this Epic is done. That list may fluctuate as requirements are discovered/negotiated.

**Comment by emersonknapp** [comment]
Complete to what we wanted to accomplish
