### ISSUE TITLE
[0.5d] Integrate cross_compile with RoboMaker

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-roadmap#159]
## Description
Work with the RoboMaker team to use ros-tooling/cross_compile in RoboMaker.

## Spike Timeboxing
0.5 Days. If there is overflow work, it will be handled as a separate user story.

## Spike Outcome
User stories if any major features are missing or need to be changed.

## Goals
The goal of this spike is to support the RoboMaker team as they work on using the cross_compile tool in the product.

**Comment by thomas-moulard** [comment]
Punted from sprint #11 to sprint #12 on 2020-02-03
