### ISSUE TITLE
Colcon-bundle daily test failure pages the oncall

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#170]
## Description

Depends on https://github.com/ros-security/aws-roadmap/issues/169

When the end to end tests fail, page the on-call for the package.

Builds should log a success or failure with Cloudwatch metrics and an alarm should be triggered in the event of a failure.

## Test Plan

* Create a failing build and receive a page.

## Documentation Plan

* Update the on-call handbook and document how to use the GH action.

## Release Plan

* Check in GitHub workflow to colcon-bundle

## Acceptance Criteria

* [x] When colcon-bundle or colcon-ros-bundle scheduled end to end tests fail, the on-call receives a page
* [x] The oncall has a handbook section for what to do when paged
* [x] The GitHub action for CW metrics is published on ros-tooling
* [x] An OSA ticket is opened to put the GH action in aws-robotics

Once all above items are checked, this story can be moved to done.

## Resources

* `aws-robotics` implementation of the cloudwatch logger [here](https://github.com/aws-robotics/rosbag-uploader-ros1/tree/master/.github/actions/cw-build-status).
* Ping Tim Robinson to walkthrough a workflow

**Comment by thomas-moulard** [comment]
Investigate if we can re-use the component in aws-robotics.

**Comment by piraka9011** [comment]
I've created an action that does this but in the meantime we can just use a repo specific GH action.
Spoke with Emerson offline to see how we can open source the action in aws-actions or similarly.

**Comment by piraka9011** [comment]
Added the cloudwatch action to colcon-bundle in [this PR](https://github.com/colcon/colcon-bundle/pull/133)

**Comment by piraka9011** [comment]
The action is hosted in [ros-tooling/action-cloudwatch-metrics](https://github.com/ros-tooling/action-cloudwatch-metrics).
The action is in colcon/colcon-bundle#137 and colcon/colcon-ros-bundle#33.
