### ISSUE TITLE
ROS2 Message Metrics (Topic Statistics)

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#171]
## Description

The Robot Operating System Version 2 (ROS2) (https://index.ros.org/doc/ros2/) does not provide capabilities to measure ROS2 message (https://design.ros2.org/articles/interface_definition.html)metrics. However, ROS1 (https://www.ros.org/) provided message metrics as Topic Statistics (http://wiki.ros.org/Topics#Topic_statistics). Roboticists, developers, users, and operators rely on message metrics to make informed decisions regarding system performance and health. 

The goal of this epic project is to provide lightweight, real-time message metrics to enable system debugging, benchmarking, and diagnosis of a ROS2 system.

Note: this epic will re-use components defined in the [System Metrics](https://github.com/ros-security/aws-roadmap/issues/4) project. 

## References

 * [internal 1 pager](https://quip-amazon.com/Eh79AnK29Sug)
 * [System Metrics Epic](https://github.com/ros-security/aws-roadmap/issues/4)
 * [System Metrics Repo](https://github.com/ros-tooling/system_metrics_collector)

**Comment by emersonknapp** [comment]
Closing since all subtasks are complete
