### ISSUE TITLE
As a ROS2 developer, I want stable CI for my GH actions so that my development workflow is not disrupted

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-roadmap#173]
## Description

Recent issues [[Example 1](https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122), [Example 2](https://github.community/t5/GitHub-Actions/Docker-build-failure-on-Ubuntu-18-04-host/m-p/33224)] with Microsoft's instances suggest that running workflows on bare metal is not ideal.

The `setup-ros` and `action-ros-ci` repos should be updated to instead use a Docker based setup for ROS to mitigate CI flakiness.

* [ ] Identify a stable Docker image to build from
* [ ] Create a new Dockerfile in the repo
* [ ] Update the `action.yml` file to use the Dockerfile

## Test Plan

* Previous testing workflows for ROS1 and ROS2 should pass

## Documentation Plan

* Docstrings
* Update README on how the action works.

## Release Plan

* Merge into `master`
* Create new release tag

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [Using Docker in a GH action](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action#create-an-action-metadata-file)

**Comment by emersonknapp** [comment]
`setup-ros-docker` meets this need
