### ISSUE TITLE
View MetricsMessage in RQT

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#174]
## Description

Implement or extend a plugin to view the [system_metrics_collector](https://github.com/ros-tooling/system_metrics_collector) [MetricsMessage](https://github.com/ros-tooling/system_metrics_collector/blob/master/metrics_statistics_msgs/msg/MetricsMessage.msg) in rqt.

Currently the only visualization exists using the [CloudWatch Metrics ROS2 agent](https://github.com/aws-robotics/cloudwatchmetrics-ros2). Using the default plotting tools in rqt does not allow a user to filter based on metrics source: this is desirable as many metrics are published to the same topic. 

Show a single plot
* x axis is time
* y axis is "metric value"
* potentially multiple lines on the plot

Use a multiselect GUI element to select
* which metrics to show
* filter by field/source

## Test Plan

* Manual testing
  * ensure multiple MetricsMessage produces can be independently viewed

## Documentation Plan

* README.md update
  * provide screenshots

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by emersonknapp** [comment]
probably more appropriate for rqt since it's not a 3d world thing?

**Comment by dabonnie** [comment]
> probably more appropriate for rqt since it's not a 3d world thing?

Yes, my mistake. Editing accordingly.

**Comment by thomas-moulard** [comment]
We have a PR in limbo which could help: https://github.com/ros-visualization/rqt_plot/pull/44

**Comment by emersonknapp** [comment]
Dropping for now until we get requests for this
