### ISSUE TITLE
Github Action Project Canaries

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#182]
## Description

Define a github action used to create a ROS2 project canary. Ideally this action will allow a canary to define its dependencies, which can be outside of the project's scope, and run them against a desired version. For example, a project may desired to use a canary on the master branch for nightly builds and to test release artifacts (e.g. apt). 

## Documents

 * well defined github action readme
 * tutorial and simple examples

## Completion Criteria

A github action that can be used to define canaries, and their dependencies, for ROS2 projects.

## References

 * [e2e test discussion](https://github.com/ros-tooling/system_metrics_collector/pull/88)

**Comment by emersonknapp** [comment]
Closing in favor of tracking elsewhere as part of operations project
