### ISSUE TITLE
Port Message Period Measurement to System Metrics Collector

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#185]
## Description

Port internal protoyping code, which measures ROS2 message period, to the system_metrics_collector package. Short term this requires refactoring the ``` message_period_moving_average_statistics``` class to use the messages and common utilities found in the [system_metrics_collector](https://github.com/ros-tooling/system_metrics_collector).

Long term we envision this class to be part of a separate package. Specifically, system_metrics_collector and the ensuing topic_statistics packages should both depend on a more generic utilities package.

## Test Plan

 * Port existing unit tests for the class

## Documentation Plan

* Document classes

## Release Plan

 * check in PR
 * put code in another folder in the system_metrics_collector project

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

**Comment by thomas-moulard** [comment]
@dabonnie add details regarding manual QA
