### ISSUE TITLE
Port ROSMovingAverageStatistics to system_metrics_collector

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#188]
## Description

Create a base class, which replaces the  ```ROSMovingAverageStatistics``` class. This base class should extend from the ```Collector``` super class, because the provides the main functionality needed for any message statistic measurement. However, the measurement window start time will be needed to be kept as a class reference.

A direct port of ```ROSMovingAverageStatistics``` is not necessary given the existing functionality implemented in the ```Collector``` class.

## Test Plan

* N/A

## Documentation Plan

* Document classes

## Release Plan

* check in PR
 * put code in another folder in the system_metrics_collector project

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

**Comment by thomas-moulard** [comment]
@dabonnie check whether we can have e2e tests for this one or not.

**Comment by dabonnie** [comment]
Updated issue given findings with @prajakta-gokhale.

**Comment by dabonnie** [comment]
Note: during implementation of https://github.com/ros-tooling/system_metrics_collector/pull/94/files, this class evolved into a pure interface. Testing is accomplished through the implemented classes.
