### ISSUE TITLE
Fix compression+splitting bug in rosbag2

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-roadmap#192]
This issue is tracking the following issues:
- [x] https://github.com/ros2/rosbag2/issues/296
- [x] https://github.com/ros2/rosbag2/issues/297

There is an in-flight PR that needs additional work to be accepted:
- [x] https://github.com/ros2/rosbag2/pull/294

**Comment by thomas-moulard** [comment]
Chat with Zach before starting this

**Comment by piraka9011** [comment]
Add `CompressionFactory` in ros2/rosbag2#311.

**Comment by piraka9011** [comment]
Implementation of `CompressionFactory` in ros2/rosbag2#313

**Comment by piraka9011** [comment]
Refactor is in ros2/rosbag2#315
