### ISSUE TITLE
Update tutorials to highlight that one should not call services from callbacks

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/aws-roadmap#193]
## Description

Update the ROS2 simple service and client tutorial (https://index.ros.org/doc/ros2/Tutorials/Writing-A-Simple-Py-Service-And-Client/) to highlight that one should not make synchronous requests to services from inside a callback (be it the callback of a subscription, service, etc.).

## Test Plan

* Follow the updated tutorial to see that it makes sense

## Documentation Plan

* The tutorial is essentially documentation in itself

## Release Plan

* Have the tutorial changes merged into the `ros2/ros2_documentation` repo

## Acceptance Criteria

* [ ] Tutorial has been written, reviewed, and merged.

Once all above items are checked, this story can be moved to done.

## Resources

* [Current tutorial](https://github.com/ros2/ros2_documentation/blob/master/source/Tutorials/Writing-A-Simple-Py-Service-And-Client.rst)
* [ROS Answers 1](https://answers.ros.org/question/343279/ros2-how-to-implement-a-sync-service-client-in-a-node/)
* [ROS Answers 2](https://answers.ros.org/question/302037/ros2-how-to-call-a-service-from-the-callback-function-of-a-subscriber/)

**Comment by thomas-moulard** [comment]
@mm318 Please groom this ticket.

**Comment by mm318** [comment]
Draft pull request opened at https://github.com/aws-ros-dev/ros2_documentation/pull/2.

**Comment by mm318** [comment]
Real pull request opened at https://github.com/ros2/ros2_documentation/pull/538 :smiley:

**Comment by thomas-moulard** [comment]
That was a quick LGTM, thanks @mm318  ;)

**Comment by mm318** [comment]
Additionally opened a pull request for the `rclpy` API docs at https://github.com/ros2/rclpy/pull/516 to add a stronger warning about not calling services from callbacks.

**Comment by mm318** [comment]
OSRF is willing to take over https://github.com/ros2/ros2_documentation/pull/538, and https://github.com/ros2/rclpy/pull/516 is merged.

This ticket may be considered done.
