### ISSUE TITLE
Define and Implement SubscriberTopicStatistic Class

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#197]
## Description

The two statistic measurements we are supporting are message age (https://github.com/ros-tooling/aws-roadmap/issues/186) and message period (https://github.com/ros-tooling/aws-roadmap/issues/185). These measurements (collectors) should be contained in a single class, i.e., the SubscriberTopicStatistics<T> class, where type T is the message type. 

Inputs, at construction time, should be

 * node name
 * node options (parameters) or subscriber topic should be a node parameter 

Note: in order to use this class inside the base subscriber (https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/subscription.hpp) care should be taken to avoid external dependencies or using core ROS2 components (circular dependency).

## Test Plan

* Manual testing
  * The class to be ported is similar to a linux measurement node. Manual testing should ensure that a test publisher is publishing data so that a message age can be measured and its results published (e.g. use ```ros2 topic echo``` to view data). 
* Port existing unit tests for the class
* End to end integration test calling CLI entrypoint
  * Use the system_metrics_collector e2e as a base 

## Documentation Plan

* README.md update

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

PROMPT (REMOVE-ME): Add here links to any relevant document e.g. design (and make sure everyone can access the docs linked here!):

* [FIXME](http://...)

**Comment by emersonknapp** [comment]
Reviewed at Sprint #17 review
