### ISSUE TITLE
Port image_transport tutorials to use ROS 2.

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-roadmap#200]
**REMOVE-ME: Fill out this and all below sections, and remove the PROMPT questions for readability.**

## Description
[The tutorial](https://github.com/ros-perception/image_common/tree/ros2/image_transport/tutorial) for `image_transport` still uses ROS 1 on the `ros2` branch. Update the tutorial to use ROS 2.

The tutorial defines 2 sets of publisher/subscriber nodes:
* `my_publisher.cpp`/`my_subscriper.cpp` which publishes a single image.
* `resized_plublisher.cpp`/`resized_subcriber.cpp` which is a plugin that resizes an image.

## Test Plan
* Manual testing; verify the tutorial works with the intended workflow.
* End to end integration test calling CLI entrypoint

## Documentation Plan
* Add a `README.md` for the tutorial

## Release Plan
* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources
* [Some work](https://github.com/zmichaels11/image_transport_demo) was done on a simpler implementation of pub/sub nodes using `image_transport`
* [ROS 1 tutorial covering this code](http://wiki.ros.org/image_transport/Tutorials)

**Comment by emersonknapp** [comment]
No longer a priority
