### ISSUE TITLE
Update code segments in image_common ROS2-Migration wiki

### ISSUE THREAD

**Issue by zmichaels11** [ros-tooling/aws-roadmap#201]
## Description
The code on [this wiki page](https://github.com/ros-perception/image_common/wiki/ROS2-Migration) does not work when built against the `ros2` branch of `image_transport`. It should be updated to correctly state how to set up `image_transport` in ROS 2.

## Test Plan
* Manual testing; code examples in wiki page build.

## Documentation Plan
* Wiki update

## Release Plan
* Wiki update

## Acceptance Criteria
* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

## Resources
* [A working demo](https://github.com/zmichaels11/image_transport_demo) was built during the rviz2 image compression spike.

**Comment by emersonknapp** [comment]
No longer a priority
