### ISSUE TITLE
[1d] Add Topic Statistics in the ROS 2 concepts wiki

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-roadmap#245]
## Description

Topic Statistics will be a new feature introduced in ROS2-F. We want users to know about this feature and have a basic understanding of what it does.

Add a Topic Statistics section in [ROS 2 Concepts](https://index.ros.org/doc/ros2/Concepts/) describing what the feature is and what to expect from it.

## Spike Timeboxing

1d

## Spike Outcome

A new section `Topic Statistics` in https://index.ros.org/doc/ros2/Concepts/

## Goals

Explain a new feature introduced in ROS2-F.

**Comment by emersonknapp** [comment]
@dabonnie note that the ros2_documentation PR should be linked to this issue https://github.com/ros2/ros2_documentation/issues/722

**Comment by dabonnie** [comment]
Can see the formatted file (merged into master) [here](https://github.com/ros2/ros2_documentation/blob/master/source/Concepts/About-Topic-Statistics.rst), not sure how often https://index.ros.org/doc/ros2/ is built.

**Comment by emersonknapp** [comment]
@dabonnie to change "empty data" to "nan" in https://index.ros.org/doc/ros2/Concepts/About-Topic-Statistics/

**Comment by emersonknapp** [comment]
Done
