### ISSUE TITLE
Create Topic Statistics Demo

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#262]
## Description

Create a Topic Statistics demo in the [ros2/demos](https://github.com/ros2/demos) repo. This should demonstrate how to enable the topic statistics feature, configure the publishing rate, and how to receive a statistics message.

## Test Plan

* Manual testing

## Documentation Plan

* new README.md for the demo package

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by emersonknapp** [comment]
This is done
