### ISSUE TITLE
Move rosbag2_bag_v2 CI to Focal

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-roadmap#265]
## Description

ROS 2 Foxy supports Ubuntu Focal, so we need to run CI for our packages on Ubuntu Focal.

This is a tracking issue to move `rosbag2_bag_v2` CI to Focal. All other packages will be migrated to Focal in https://github.com/ros-tooling/aws-roadmap/issues/247, but as per @thomas-moulard's [comment](https://github.com/ros-tooling/aws-roadmap/issues/247#issuecomment-622683744) we want to track this repo separately because its CI needs to be fixed before it can be migrated.

## Test Plan

* CI is green on Focal

## Documentation Plan

N/A

## Design Sign-Off

N/A

## Release Plan

Merge PR changing Action CI settings (when green)

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [rosbag2_bag_v2 CI](https://github.com/ros2/rosbag2_bag_v2/actions)

**Comment by emersonknapp** [comment]
Closing in favor of https://github.com/ros2/rosbag2_bag_v2/issues/22
