### ISSUE TITLE
[2d] Investigate why pluginlib does not work on armhf

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#266]
## Description

Since enabling the armhf builds last year - features that use class_loader/pluginlib do not work in that build, though they do build successfully.

This includes but is not limited to:
* rosbag2 plugins (and therefore its functionality)
* composable component nodes
* rviz and rqt plugins (not very important, it is not really expected that users run OpenGL GUIs on 32 bit platforms)

## Spike Timeboxing

2 days

## Spike Outcome

This spike is there to give time to explore the problem and identify the sources of the problem, if not their exact solutions.

 * Epic or stories to track the work of enabling this feature on armhf

## Goals

some notes
* it's probably something in Poco, or whatever we replaced it with for dynamic library loading.
* the build itself does not seem to work properly for rclcpp_components, in armhf builds the component binaries are not created, only the component libraries.

### Minimum Repro Case

When trying to build the composability demos on armhf, the component node binaries were not produced.

**Comment by mm318** [comment]
Deprioritizing ARMHF-related issues.

**Comment by emersonknapp** [comment]
Not currently supporting the armhf builds - closing this until it is on our roadmap
