### ISSUE TITLE
Support Windows CI in Github Actions

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#268]
## Description

Similar to Linux and OSX, provide support for Windows CI in github actions ([setup-ros](https://github.com/ros-tooling/setup-ros), [action-ros-ci](https://github.com/ros-tooling/action-ros-ci)). This is a necessary part of CI given [ROS2 platform support](https://www.ros.org/reps/rep-2000.html#targeted-platforms). 

Note: this should also fix the follow issue: https://github.com/ros-tooling/action-ros-ci/issues/79 

## Documents

 - README update in the relevant repos for Windows support

## Completion Criteria

REMOVE ME: Instead of creating a list here, start creating issues under this epic, this will be the TO-DO list for this Epic. When all children are done, this Epic is done. That list may fluctuate as requirements are discovered/negotiated.

**Comment by emersonknapp** [comment]
Closing in favor of trackingon the project in ros-tooling/action-ros-ci#79
