### ISSUE TITLE
[3d] ROS2 OSRF Testing: OSX Executables

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#273]
## Description

Following the [ROS2 OSRF Testing Matrix](https://docs.google.com/spreadsheets/d/1EzDKMGoYopKuGWmzceXTVJ1zWqq1Wxw2jIGsh3CawAQ/edit#gid=1713002348), test the ROS2 executables with the following configuration:

 - system: OSX
 - RMW: FastRTPS, Connext, CycloneDDS

Progress for each item should be tracked on the OSRF Testing Matrix per their guidelines. The first column to address should be testing via the fat archive and not from source (as OSX currently has known issues).

## Spike Timeboxing

3 days

## Spike Outcome

 * Best effort testing of the ROS2 executables using OSX.

**Comment by thomas-moulard** [comment]
There are a few failed tasks without a ticket, are those reported to OR?

**Comment by zmichaels11** [comment]
Need connext?
