### ISSUE TITLE
ROS2 Foxy QA

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#274]
## Description

Support the ROS2 Foxy release by providing QA for the core packages and AWS Foundations / ros-tooling owned features. These features include:

 - rclcpp topic statistics
 - rosbag2 splitting
 - rosbag2 QoS
 - incompatible QoS callbacks

**Comment by emersonknapp** [comment]
High level callout for OSX setup instructions: https://github.com/ros2/ros2_documentation/issues/727 the RTI connext link is incorrect

**Comment by emersonknapp** [comment]
High level callout for Windows setup instructions: Python version is wrong in instructions https://github.com/ros2/ros2_documentation/pull/723

**Comment by emersonknapp** [comment]
More windows setup instructions fixes https://github.com/ros2/ros2_documentation/pull/732

**Comment by emersonknapp** [comment]
Done!
