### ISSUE TITLE
QA Rosbag2: Splitting and Compression

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#275]
## Description

Record high volume data using rosbag 2 record with compression no splitting and splitting enabled for various split sizes, and splitting for various sizes without compression. Verify that the split bag files can be played back.

The following configurations should be tested to ensure the feature works on all platforms and middlewares:

|  *Operating System* |
|-------------------|
|   OSX |
|  Windows |
|  Linux x86_64 |  

|  *RMW* |
|-------------------|
|   FastRTPS |
|  Connext |
|  CycloneDDS |  

**Priority**
 - Linux + default RMW, non default RMW
 - Windows + default RMW, non default RMW
 - OSX + default RMW, non default RMW

## Spike Timeboxing

1.5 days

## Spike Outcome

 * github tickets if any bugs are found
 * document (or comment update here) how to reproduce manual tests

**Comment by piraka9011** [comment]
To reproduce:

Install the prerequisites and [fat binaries](https://index.ros.org/doc/ros2/Installation/Prerelease-Testing/) on the target platform. 

```
ros2 topic pub /test_topic std_msgs/String "data: Hello World"
# TODO
```

- Linux
  - FastRTPS
    - [ ] record
    - [ ] playback
  - RTI Connext
    - [ ] record
    - [ ] playback
  - Cyclone DDS
    - [ ] record
    - [ ] playback
- OSX
  - FastRTPS
    - [ ] record
    - [ ] playback
  - RTI Connext
    - [ ] record
    - [ ] playback
  - Cyclone DDS
    - [ ] record
    - [ ] playback
- Windows
  - FastRTPS
    - [ ] record
    - [ ] playback
  - RTI Connext
    - [ ] record
    - [ ] playback
  - Cyclone DDS
    - [ ] record
    - [ ] playback

**Comment by piraka9011** [comment]
Opened ros2/rosbag2#428 to enhance the UX when specifying a split size.

**Comment by prajakta-gokhale** [comment]
Opened https://github.com/ros2/rosbag2/issues/432 for incorrect behaviour on setting invalid splitting size, when using splitting and compression together.
