### ISSUE TITLE
Add rosbag2 splitting and compression info to README

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#278]
## Description

Add compression option and splitting option details to the rosbag2 project [readme](https://github.com/ros2/rosbag2). 

## Test Plan

* Manually test the documentation provided in the readme by executing the commands on a local system

## Documentation Plan

* README.md update

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by emersonknapp** [comment]
Closing in favor of https://github.com/ros2/rosbag2/issues/478
