### ISSUE TITLE
QA Topic Statistics: Configuration

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#279]
## Description

Verify options (topic name, publish period, enable / disable state) are configurable. Verify correct behavior when statistics are disabled.

The following configurations should be tested to ensure the feature works on all platforms and middlewares:

|  *Operating System* |
|-------------------|
|   OSX |
|  Windows |
|  Linux x86_64 |  

|  *RMW* |
|-------------------|
|   FastRTPS |
|  Connext |
|  CycloneDDS |  

**Priority**
 - Linux + default RMW, non default RMW
 - Windows + default RMW, non default RMW
 - OSX + default RMW, non default RMW

## Spike Timeboxing

0.5 days

## Spike Outcome

 * github tickets if any bugs are found
 * document (or comment update here) how to reproduce manual tests

**Comment by dabonnie** [comment]
Take code like the talker demo and manually change the subscription options.

**Comment by emersonknapp** [comment]
- Linux
  - FastRTPS
    - [x] rclcpp
    - [x] rclpy
  - RTI Connext
    - [x] rclcpp
    - [x] rclpy
  - Cyclone DDS
    - [x] rclcpp
    - [x] rclpy
- OSX
  - FastRTPS
    - [ ] rclcpp
    - [ ] rclpy
  - RTI Connext
    - [ ] rclcpp
    - [ ] rclpy
  - Cyclone DDS
    - [ ] rclcpp
    - [ ] rclpy
- Windows
  - FastRTPS
    - [ ] rclcpp
    - [ ] rclpy
  - RTI Connext
    - [ ] rclcpp
    - [ ] rclpy
  - Cyclone DDS
    - [ ] rclcpp
    - [ ] rclpy

To reproduce:

Install the prerequisites and [fat binaries](https://index.ros.org/doc/ros2/Installation/Prerelease-Testing/) on the target platform.

**Comment by dabonnie** [comment]
FYI we only implemented in rclcpp and not rclpy.

**Comment by emersonknapp** [comment]
Progress tracking here because markdown is hard https://docs.google.com/spreadsheets/d/1xlDpkV_n9cCc9rOpJBsJ5KNkfjGQDXItqp4XY18oyOI/edit#gid=1713002348

**Comment by emersonknapp** [comment]
Testing notes - Linux:

* Build retrieved from:
  * ci.ros2.org
* Build test workspace
  * `source ros2-linux/setup.bash`
  * Clone this repository https://github.com/emersonknapp/foxytest into src/
  * `colcon build`
* Run test, each command in separate shell
  * `ros2 topic pub /chatter std_msgs/String "data: hello"`
  * `ros2 run topic_statistics_test chatter_stats`
  * `ros2 topic echo ${STATS_TOPIC}`

Twiddle values in chatter_stats.cpp

**Comment by emersonknapp** [comment]
Enable/disable: 
* set on, see topic pub
* set off, see no topic

Publish Period:
Expectation: `ros2 topic hz /statistics` gives `2 * 1 / period` (2 messages are published each cycle)
* Works: 2s, 500ms, 1ms
* Fails at compile: 20us
* Fails at runtime: -1s
* 0ms publishes at apparently maximum loop speed

Topic Name
Expectation: `ros2 topic echo topicname` prints messages
* Works: "/staty", "tostastics", "/topic/stats"
* Fails at runtime: "", "top-ic"

**Comment by emersonknapp** [comment]
Mac fat binary: https://ci.ros2.org/view/packaging/job/packaging_osx/1865/artifact/ws/ros2-package-osx-x86_64.tar.bz2

Follow setup instructions at https://index.ros.org/doc/ros2/Installation/Foxy/macOS-Install-Binary/ (skip rviz rqt sros deps)
No other differences from Linux

**Comment by emersonknapp** [comment]
Windows: using https://ci.ros2.org/view/packaging/job/packaging_windows/1754/artifact/ws/ros2-package-windows-AMD64.zip

Followed setup instructions for https://index.ros.org/doc/ros2/Installation/Foxy/Windows-Install-Binary/ - skipping opencv and qt stuff

Using "Developer Command Prompt for VS2019" for all commands - multiple windows open simultaneously sourcing the same build. Building same repo as other platforms after running `.\ros2-windows\setup.bat`

**Comment by emersonknapp** [comment]
Created https://github.com/ros2/ros2_documentation/pull/723 to enable windows testing (using manual packaging build from https://ci.ros2.org/view/packaging/job/packaging_windows/1754/)

**Comment by dabonnie** [comment]
Patch as a result of this testing: https://github.com/ros2/rclcpp/pull/1151#pullrequestreview-424032892
