### ISSUE TITLE
QA Topic Statistics: Check For Published Data

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#280]
## Description

Obtain statistics for various messages that do not use a timestamped message header (majority of ROS messages, e.g. run the talker / subscriber demo and enable statistics). 
Obtain statistics for various messages that use a timestamped message header, e.g. IMU data: this will require a custom publisher.

The following configurations should be tested to ensure the feature works on all platforms and middlewares:

|  *Operating System* |
|-------------------|
|   OSX |
|  Windows |
|  Linux x86_64 |  

|  *RMW* |
|-------------------|
|   FastRTPS |
|  Connext |
|  CycloneDDS |  

**Priority**
 - Linux + default RMW, non default RMW
 - Windows + default RMW, non default RMW
 - OSX + default RMW, non default RMW

## Spike Timeboxing

1 days

## Spike Outcome

 * github tickets if any bugs are found
 * document (or comment update here) how to reproduce manual tests

**Comment by emersonknapp** [comment]
Setup

* Build retrieved from:
  * ci.ros2.org
* Build test workspace
  * `source ros2-linux/setup.bash`
  * Clone this repository https://github.com/emersonknapp/foxytest into src/
  * `colcon build`
* Run test, each command in separate shell
  * `ros2 topic pub /chatter std_msgs/String "data: hello"`
  * `ros2 run topic_statistics_test chatter_stats`
  * `ros2 topic echo ${STATS_TOPIC}`

Twiddle values in chatter_stats.cpp

**Comment by emersonknapp** [comment]
Opened 
https://github.com/ros-tooling/libstatistics_collector/issues/28
https://github.com/ros-tooling/libstatistics_collector/issues/27

**Comment by emersonknapp** [comment]
Opened https://github.com/ros-tooling/libstatistics_collector/issues/29

**Comment by emersonknapp** [comment]
Other than behavioral uncertainty no issues, seems to be working. Used same setup as per #279

**Comment by emersonknapp** [comment]
Was able to test Connext on Windows by using the eval license from the Linux install - all working as expected
