### ISSUE TITLE
QA CLI Node Info

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#291]
## Description

Use command line tools and launch files to verify duplicate node names and enhanced QoS info per:

 * [x] https://github.com/ros2/ros2cli/pull/463 (`ros2 node info`)
 * [x] https://github.com/ros2/ros2cli/pull/462 (`ros2 node list`)
 * [x] https://github.com/ros2/launch_ros/pull/127 (`launch` log WARNING)
 * [ ] https://github.com/ros2/ros2/issues/830

The following configurations should be tested to ensure the feature works on all platforms and middlewares:

|  *Operating System* |
|-------------------|
|   OSX |
|  Windows |
|  Linux x86_64 |  

|  *RMW* |
|-------------------|
|   FastRTPS |
|  Connext |
|  CycloneDDS |  

**Priority**
 - Linux + default RMW, non default RMW
 - Windows + default RMW, non default RMW
 - OSX + default RMW, non default RMW

## Spike Timeboxing

0.5 days

## Spike Outcome

 * github tickets if any bugs are found
 * document (or comment update here) how to reproduce manual tests

**Comment by prajakta-gokhale** [comment]
With default rmw implementation (fastrtps):

| Feature  | Linux | macOS | Windows |
| ------------- | ------------- | ------------- | ------------- |
| `ros2 node list`  | ✅   | ✅  |. |
| `ros2 node info`  | ✅   | ✅  |. |
| `launch` log WARNING |. |. |. |

**Comment by prajakta-gokhale** [comment]
Using fat binary generated by https://ci.ros2.org/view/packaging/job/packaging_windows/1758/
