### ISSUE TITLE
As a rosbag2 developer, I need to have a way to measure and compare the performance against rosbag1, so that I can make assertions about its performance

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#62]
## Description

rosbag2 performance has been reported as not being good enough currently. 

Define _two_ key performance criteria and create a way to repeatedly measure them for rosbag1 and rosbag2, so that their performance can be compared.

**Comment by emersonknapp** [comment]
Iceboxing until more concrete use case and goals are negotiated

**Comment by zmichaels11** [comment]
@piraka9011 write user stories for this epic

**Comment by piraka9011** [comment]
Metrics we want to track:

* Disk usage
* Memory usage
* CPU usage
* Database transaction time (R/W)
* Compression time
* Playback time

**Comment by dabonnie** [comment]
Closing this in favor of https://github.com/ros-tooling/aws-roadmap/issues/150. We currently have metrics defined to measure performance and an internal review meeting to discuss said metrics today.
