### ISSUE TITLE
[2d] As a ROS user, I want to prevent multiple nodes from having the same name (node name uniqueness)

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#77]
## Description

"As a ROS 2 user, I want to prevent multiple nodes
from having the same name so that I avoid hard to
debug issues and potentially unsafe behaviors"

An existing "request for design" is here, but the future is very uncertain
https://github.com/ros2/design/issues/187

We want to make the "non-unique-node-name" problem as minimal as we can within a constrained time frame. 

## Exit Criteria

* [x] Research what reasonable interventions we can perform before ROS2F to mitigate the issues with node name uniqueness
* [x] Document findings, explaining considered paths and final decision
* [x] Create stories tracking work that is decided to be done

**Comment by thomas-moulard** [comment]
Proposals:

- modify ROS core packages to log a warning if multiple nodes with the same name are present on the network
- modify ROS2 launch to emit a warning if multiple nodes with the same name are present in a particular launch configuration
- modify `ros2 node` verb to print output in a way that nodes with the same node can be differentiated (host ip + pid?). `node` -> `node[127.0.0.1/1234]`

**Comment by thomas-moulard** [comment]
The original issue is this one: https://github.com/ros2/ros2cli/issues/279

**Comment by emersonknapp** [comment]
Resolved via spike report and new stories
