### ISSUE TITLE
As a ROS 2 user, I want improved Mac OS support so that I can develop software on my environment of choice

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#92]
## Description

"As a ROS 2 user, I want improved Mac OS support
so that I can develop software on my environment of
choice"

REMOVE ME: A short description of this large feature / feature set. An epic should still be well scoped and have a clear concept of where "finished" is.

## Documents

REMOVE ME: Link or include any designs that inform this Epic's completion criteria.

## Completion Criteria

REMOVE ME: Instead of creating a list here, start creating issues under this epic, this will be the TO-DO list for this Epic. When all children are done, this Epic is done. That list may fluctuate as requirements are discovered/negotiated.

**Comment by thomas-moulard** [comment]
Deprioritized.
