### ISSUE TITLE
As a ROS 2 user, I want to be able to call services inside callbacks so that I can write complex callbacks easily

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#93]
## Description

"As a ROS 2 user, I want to be able to call services
inside callbacks so that I can write complex
callbacks easily"

REMOVE ME: Fill out this and all below sections, and remove the PROMPT questions for readability.

PROMPT: A concise, concrete, finishable, description of the feature to be built.

## Test Plan

PROMPT: What tests should be created to support this feature?
* Manual testing
* Unit test for new classes
* End to end integration test calling CLI entrypoint
* ...

## Documentation Plan

PROMPT: What documentation updates need to be made to support this feature? e.g.
* README.md update
* wiki update
* design doc PR
* ...

## Release Plan

PROMPT: What release work needs to be done to finish this feature? e.g.
* check in PR
* bloom release

## Acceptance Criteria

PROMPT: Clearly defined checklist of things that need to be done to call this task complete. Can include items from all above sections. 
* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

PROMPT: Add here links to any relevant document e.g. design (and make sure everyone can access the docs linked here!):*
* [FIXME](http://...)

**Comment by thomas-moulard** [comment]
Waiting for repro code before investigating this.

**Comment by emersonknapp** [comment]
I believe this issue may be in reference to this line https://github.com/ros2/rclpy/blob/master/rclpy/rclpy/client.py#L69 

The _synchronous_ service call API is not recommended in callbacks because it may block indefinitely and eat up your callback threads, hence the deadlock.

A potential solution to closing this issue is a demo/example that uses `client.call_async` in a callback to show the recommended way to perform these operations.

**Comment by emersonknapp** [comment]
Relevant conversation https://answers.ros.org/question/343279/ros2-how-to-implement-a-sync-service-client-in-a-node/

**Comment by thomas-moulard** [comment]
@mm318 Seems like Emerson has some ideas about what needs to be done there. Would you mind sync-ing with him?

**Comment by mm318** [comment]
Is this an issue with `rclpy` only? What about `rclcpp`? Or a system with a mix of `rclcpp`/`rclpy`?

**Comment by mm318** [comment]
Created spike for this milestone at https://github.com/ros-tooling/aws-roadmap/issues/184.

**Comment by mm318** [comment]
The discussion following the spike reached the following conclusion on possible resolution:
- Better education on ROS2 programming best practices (through documentation, tutorials, etc.)
  - Currently, there's only some obscure mentions of the issue on ROS Answers ([here](https://answers.ros.org/question/343279/ros2-how-to-implement-a-sync-service-client-in-a-node/) and [here](https://answers.ros.org/question/302037/ros2-how-to-call-a-service-from-the-callback-function-of-a-subscriber/))
- Address the `rclpy` API:
  - Deprecate the synchronous `Client.call()` API
    - Emit a warning whenever `Client.call()` is used
  - Remove the synchronous `Client.call()` API altogether (even `rclcpp` does not have an equivalent)

Immediate next step is to start a discourse post regarding this issue.

**Comment by mm318** [comment]
Discourse post was created here: https://discourse.ros.org/t/synchronous-request-to-service-in-callback-results-in-deadlock/12767
